// <auto-generated />
namespace Workwise.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class addCompanyName : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addCompanyName));
        
        string IMigrationMetadata.Id
        {
            get { return "202002281821507_addCompanyName"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
